version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php_service
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - bas-network
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - bas-network
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST= db
      - PMA_PASSWORD= ${MYSQL_ROOT_PASSWORD}
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'admin'
      MYSQL_ROOT_PASSWORD: 'Test3211'
      #SERVICE_TAGS: dev
      #SERVICE_NAME: mysql
    env_file:
      - .env
    volumes:
      #- lbdata:/var/lib/mysql/
      #- ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db-initialization/laravel.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - bas-network
#Docker Networks
networks:
  bas-network:
    driver: bridge
#Volumes
volumes:
  lbdata:
    driver: local